### ISSUE TITLE
make it work in observable

### ISSUE THREAD

**Issue by Fil** [Fil/d3-inertia#13]
- [x] not having to set window.projection
- [x] not having to set window.versor
- [x] properly dispose of the process when the cell is re-executed

https://beta.observablehq.com/@fil/using-d3-inertia-with-observable

**Comment by Fil** [comment]
Another warning is
<img width="453" alt="capture d ecran 2018-04-05 a 23 50 37" src="https://user-images.githubusercontent.com/7001/38393785-3a001214-392c-11e8-9588-b4bb8bc36bcd.png">
<img width="395" alt="capture d ecran 2018-04-05 a 23 50 24" src="https://user-images.githubusercontent.com/7001/38393786-3a2e7d16-392c-11e8-865c-0d83191cc7b8.png">

**Comment by mbostock** [comment]
Here’s what I used to get it to work, starting with my [orthographic example](https://beta.observablehq.com/@mbostock/d3-orthographic):

```js
d3 = {
  // TODO Version pinning for require.
  // TODO Change d3-inertia to declare its dependency on versor.
  window.versor = await require("versor");
  return require("d3-selection", "d3-fetch", "d3-geo", "d3-inertia");
}
```

If d3-inertia declared its dependency on versor, then the versor dependency would be loaded automatically rather than needing to be preloaded and set as a global.

Unfortunately, Observable doesn’t currently allow you to pin version numbers when requiring a library that has dependencies. For example, if you pin the major version number of d3-selection by requiring `d3-selection@1` instead of `d3-selection` (and this is usually a good idea because it prevents your code from breaking when a new major version is released), then when d3-inertia says it depends on d3-selection, you end up with two copies because Observable’s require isn’t smart enough to realize that `d3-selection@1` and `d3-selection` are the same thing. See observablehq/notebook-stdlib#27.

Then I declared the projection as mutable so d3-inertia can change it and trigger the map to redraw:

```js
mutable projection = d3.geoOrthographic()
    .rotate([100, -40])
    .translate([width / 2, width / 2])
    .fitExtent([[5, 5], [width - 5, width - 5]], {type: "Sphere"})
    .precision(0.1)
```

Here’s the inertia definition:

```js
inertia = {
  // TODO Remove d3-inertia’s requirement for a global projection.
  window.projection = mutable projection;
  return d3.geoInertiaDrag(d3.select(map), () => {
    mutable projection = mutable projection;
  });
}
```

I guess if we wanted to handle invalidation we’d add something like this?

```js
invalidation.then(() => d3.select(map).on(".drag", null));
```

**Comment by Fil** [comment]
The warning in my [first comment](https://github.com/Fil/d3-inertia/issues/13#issuecomment-379087912) arises in https://beta.observablehq.com/@fil/toblers-hyperelliptical-projection when I load `d3`with 
```
require("d3", "d3-geo-projection", "d3-inertia")
```

but it goes away with
```
require("d3-selection", "d3-geo", "d3-fetch", "d3-geo-projection", "d3-inertia")
```

so prolly not a d3-inertia bug

**Comment by mbostock** [comment]
Right, you can’t use the `d3` default bundle in conjunction with plugins because that has the same duplicate module issue: require isn’t smart enough to know that the `d3-selection` needed by d3-inertia is the same as the already-loaded `d3`.

We could fix these with require configs, but that’s putting a big burden on the user. Mostly this will go away if everyone switches to ES modules and imports, as unpkg already does import rewriting using package.json. (I need to switch the D3 modules to expose ES module bundles so that loading `d3` as an ES module only triggers 30 requests instead of 500+.)
